"""A workspace where each subsystem's check takes real time to run.

This is the one case our earlier benchmarks left open. Fan-out lost on a small
project and on a 444-file one, and the reason was always the same: a child costs
~36k tokens and ~30s of session startup, and there was nothing for that to
amortise against, because a competent agent greps rather than reads.

Here there is. Each subsystem ships a checker that blocks for `SUITE_SECONDS`
before it can report -- the shape of a build or a test suite. Serial work cannot
be grepped away, so if fan-out has a regime at all, it is this one.

The sleep models I/O-bound CI honestly: the agent cannot shortcut it, and it is
told not to edit the checker. Whether it edited it anyway is measured, not
assumed -- `verify()` restores the original checkers before grading and reports
any that were tampered with.
"""

from __future__ import annotations

import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

SUITE_SECONDS = 45

SUBSYSTEMS = {
    "parser": ("split_fields", "a,b,,c", ["a", "b", "", "c"], "empty fields are dropped"),
    "pricing": ("total_cents", [199, 250, 1], 450, "the last item is skipped"),
    "routing": ("shortest_hops", None, 3, "an off-by-one in the hop count"),
    "cache": ("evict_oldest", None, ["b", "c"], "the wrong end of the queue is evicted"),
}

# Each core module has exactly one planted bug, small enough to fix quickly so
# that fix time does not swamp the thing being measured: the suite wall clock.
CORES = {
    "parser": '''\
def split_fields(line):
    """Split a comma-separated line into fields."""
    return [part for part in line.split(",") if part]
''',
    "pricing": '''\
def total_cents(items):
    """Sum the price of every item, in cents."""
    total = 0
    for index in range(len(items) - 1):
        total += items[index]
    return total
''',
    "routing": '''\
GRAPH = {"a": ["b"], "b": ["c"], "c": ["d"], "d": []}


def shortest_hops(start="a", goal="d"):
    """Number of hops from start to goal."""
    seen, frontier, hops = {start}, [start], 0
    while frontier:
        if goal in frontier:
            return hops + 1
        nxt = []
        for node in frontier:
            for neighbour in GRAPH.get(node, []):
                if neighbour not in seen:
                    seen.add(neighbour)
                    nxt.append(neighbour)
        frontier, hops = nxt, hops + 1
    return -1
''',
    "cache": '''\
def evict_oldest(keys, keep=2):
    """Drop the oldest entries, keeping the `keep` most recent."""
    return keys[:keep]
''',
}

CHECKER = '''\
"""Checks {name}/. Blocks like a real suite before it can report.

DO NOT EDIT THIS FILE. It is the acceptance test.
"""
import sys
import time
from pathlib import Path

time.sleep({seconds})

sys.path.insert(0, str(Path(__file__).resolve().parent))
import core

{body}
print("{name}: OK")
'''

BODIES = {
    "parser": 'assert core.split_fields("a,b,,c") == ["a", "b", "", "c"], core.split_fields("a,b,,c")',
    "pricing": "assert core.total_cents([199, 250, 1]) == 450, core.total_cents([199, 250, 1])",
    "routing": "assert core.shortest_hops() == 3, core.shortest_hops()",
    "cache": 'assert core.evict_oldest(["a", "b", "c"]) == ["b", "c"], core.evict_oldest(["a", "b", "c"])',
}

README = """\
# platform

Four independently owned subsystems. Each has an acceptance check that takes
about {seconds} seconds to run, because it exercises the whole subsystem.

{rows}

Run one with `python3 <name>/check.py`. Do not edit any `check.py`.
"""


def build(root: Path, seconds: int = SUITE_SECONDS) -> dict[str, str]:
    """Create the workspace; return each checker's sha256 so tampering is visible."""
    if root.exists():
        shutil.rmtree(root)
    digests: dict[str, str] = {}
    for name in SUBSYSTEMS:
        directory = root / name
        directory.mkdir(parents=True)
        (directory / "core.py").write_text(CORES[name], encoding="utf-8")
        checker = CHECKER.format(name=name, seconds=seconds, body=BODIES[name])
        (directory / "check.py").write_text(checker, encoding="utf-8")
        digests[name] = hashlib.sha256(checker.encode()).hexdigest()

    rows = "\n".join(f"    {name}/    {SUBSYSTEMS[name][0]}" for name in SUBSYSTEMS)
    (root / "README.md").write_text(
        README.format(seconds=seconds, rows=rows), encoding="utf-8"
    )
    return digests


def verify(root: Path, digests: dict[str, str], seconds: int = 0) -> dict[str, object]:
    """Restore the original checkers, then run them. Tampering is reported, not punished."""
    tampered = []
    for name in SUBSYSTEMS:
        path = root / name / "check.py"
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        normalized = CHECKER.format(name=name, seconds=seconds, body=BODIES[name])
        # Accept either the original or what a previous verify() already wrote,
        # so grading twice does not accuse the agent of our own edit.
        allowed = {digests[name], hashlib.sha256(normalized.encode()).hexdigest()}
        if hashlib.sha256(current.encode()).hexdigest() not in allowed:
            tampered.append(name)
        # Grade against the original, with the sleep removed: we are measuring
        # whether the bug was fixed, not paying for the wait a second time.
        path.write_text(normalized, encoding="utf-8")

    passing = []
    for name in SUBSYSTEMS:
        proc = subprocess.run(
            [sys.executable, str(root / name / "check.py")],
            capture_output=True, timeout=120, check=False,
        )
        if proc.returncode == 0:
            passing.append(name)
    return {"passing": passing, "passed": len(passing), "tampered": tampered}
