"""Schedule - one-time or cron prompt scheduling."""

from __future__ import annotations


class Schedule:
    async def create(self, prompt: str, *, at: str | None = None, cron: str | None = None) -> dict: ...
    async def list(self) -> list[dict]: ...
    async def delete(self, id: str) -> dict: ...
